#!/bin/python3
# vim:ts=2:sw=2:noet

from copy import deepcopy
from decimal import Decimal as dec
import statistics
from matplotlib import subprocess
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import os
import dpf

mpl.rcParams['pdf.fonttype'] = 42
mpl.rcParams['ps.fonttype'] = 42

def read_folder(foldername, arg, insert_flag=False):
	N, M, K, step = arg
	res_hundredtimes = []
	for _ in range(len(funcname_list)):
		res_hundredtimes.append([])
	print(foldername)
	for times in range(10):
		original_data_file = open(f'{foldername}/{times}.original.txt')
		original_data = [pl[:-2].split('\t') for pl in original_data_file.readlines()]
		original_data = [[dec(demand) for demand in pl] for pl in original_data]

		i = 0
		for funcname in funcname_list:
			file = open(f'{foldername}/{times}.{funcname}.txt')
			lines = file.readlines()

			ppl_seq = lines[3][1:-2]
			ppl_seq = [int(seq) for seq in ppl_seq.split(', ')]

			ppl = [pl[:-2].split('\t') for pl in lines[4:]]
			ppl = [[dec(demand) for demand in pl] for pl in ppl]

			pls = []
			if funcname == 'GreedyTheRecalculation' or (insert_flag == True and funcname != 'RandomAttack'):
				seq_order = list(range(len(ppl_seq)))
				sorted(seq_order, key=lambda x: ppl_seq[x])
				pls = deepcopy(original_data)
				for seq in seq_order:
					pls.insert(ppl_seq[seq], ppl[seq])
			elif funcname == 'RandomAttack':
				pls = deepcopy(original_data)
			else:
				pls = ppl

			sim_arg = (N * step, N, M, pls)

			c = 0
			if funcname == 'RandomAttack' or funcname == 'NaiveGreedy':
				complete_pl_list = dpf.Simulation(sim_arg=sim_arg, verbose=False)
				for seq in ppl_seq:
					if seq in complete_pl_list:
						c += 1
			else:
				c = K
			res_hundredtimes[i].append(c / K)
			i += 1

	return res_hundredtimes

def draw_success_ratio(
	res_dicts: list,
	N_list = [50, 100, 150, 200, 250],
	M_list = [10],
	Kperc_list = [0.3],
	step_list = [1.0],
):
	foldername = 'EVALUATION/' + imagefolder
	subprocess.run(['mkdir', '-p', foldername])

	## Wei: 修改图的大小
	plt.rcParams["figure.figsize"] = 11, 5

	args = [
		(N, M, step)
		for N in N_list
		for M in M_list
		for step in step_list
	]

	for arg in args:
		N, M, step = arg
		mean = [[[0 for _ in range(len(Kperc_list))] for _ in range(len(funcname_list))] for _ in range(2)]
		stdev = [[[0 for _ in range(len(Kperc_list))] for _ in range(len(funcname_list))] for _ in range(2)]
		for i in range(len(Kperc_list)):
			K = int(Kperc_list[i] * N)
			res = [[], []]
			res[0] = res_dicts[0][(N, M, K, step)]
			res[1] = res_dicts[1][(N, M, K, step)]
			for k in range(2):
				for j in range(len(res[0])):
					mean_func, stdev_func = res[k][j]
					mean[k][j][i] = mean_func
					stdev[k][j][i] = stdev_func
		fig, axes = plt.subplots(1, 2, sharex=True, sharey=True)

		total_width, n = 0.08, 5
		width = total_width / n
		x = np.arange(n) / 10
		x = x - (total_width - width) / 2
		for k in range(2):
			for i in [0, 1, 5, 2, 3, 4]:
				axes[k].bar(x + i * width, mean[k][i], width=width, label=method_list[i], color=colors[i])

		titles = ['mice 75%, elephant 25%', 'mice 0%, elephant 100%']
		for k in range(2):
			axes[k].set(xlabel=r'$K/N$', ylabel='Success Ratio')
			axes[k].set_xticks(ticks=Kperc_list)
			axes[k].set_yticks([i * 2 / 10 for i in range(6)])
			axes[k].set_title(titles[k], fontsize='medium')
			# axes[k].grid()
			# axes[k].tick_params(axis='both', which='major', labelsize=9)
			# axes[k].tick_params(axis='both', which='minor', labelsize=9)

		plt.tight_layout()

		handles, labels = axes[0].get_legend_handles_labels()
		lgd = fig.legend(handles, labels, loc='center left', fontsize='medium', 
	     	bbox_to_anchor=(1.0, 0.5), ncol=1, fancybox=False, shadow=False, frameon=False)
		figurename = f'{foldername}/Kperc_N_{N}_M_{M}_step_{step}.pdf'
		plt.savefig(figurename, format='pdf', bbox_extra_artists=(lgd,), bbox_inches='tight')
		plt.clf()

def Draw():
	parent_folder1 = './EVALUATION/DATA.MICE.AND.ELEPHANT.1/'
	parent_folder2 = './EVALUATION/DATA.MICE.AND.ELEPHANT.2/'

	N_list = [50, 100, 150, 200, 250]
	N_list = [100]
	M_list = [5, 10, 15, 20, 25, 30]
	M_list = [10]
	Kperc_list = [0.1, 0.2, 0.3, 0.4, 0.5]
	Kperc_list = [0.1, 0.3, 0.5]

	args = [
		(N, M, int(Kperc * N), 1.0)
		for N in N_list
		for M in M_list
		for Kperc in Kperc_list
	]

	res_dict1 = {}
	res_dict2 = {}
	def read_big_folder(parent_folder, insert_flag=False):
		res_dict = {}
		for arg in args:
			N, M, K, step = arg
			foldername = parent_folder + f'N_{N}_M_{M}_K_{K}_step_{step}'
			res_hundredtimes = read_folder(foldername, arg, insert_flag)
			y = [] # [(mean1, stdev1), (mean2, stdev2), (mean3, stdev3)]
			for i in range(len(funcname_list)):
				mean = statistics.mean(res_hundredtimes[i])
				stdev = statistics.stdev(res_hundredtimes[i])
				# print(mean, stdev, funcname_list[i])
				y.append((mean, stdev))
			res_dict[arg] = y
		return res_dict
	res_dict1 = read_big_folder(parent_folder1, insert_flag=False)
	res_dict2 = read_big_folder(parent_folder2, insert_flag=True)

	draw_success_ratio([res_dict1, res_dict2], N_list, M_list, Kperc_list)

if __name__ == '__main__':
	funcname_list = [
		'RandomAttack',
		'NaiveGreedy',
		'BlockGreedy',
		'DynamicSequentialAttack_std',
		'DynamicSequentialAttack_mod',
		'GreedyTheRecalculation',
	]
	method_list = [
		'Random',
		'Greedy',
		'BRA-W',
		'DSA-ds',
		'DSA-bg',
		'BRA',
	]
	markers = ['o', '^', 's', 'd', 'x', '|']
	colors = ['#262322', '#408EC3', '#A763B0', '#008D00', '#FF8700', '#FF2600']
	linestyles = ['dashdot', 'dashdot', 'solid', 'dashed', 'dashed', 'solid']
	yticks = np.arange(0, 1.1, 0.1)

	plt.rcParams['pdf.fonttype'] = 42
	plt.rcParams['ps.fonttype'] = 42
	plt.rcParams['figure.figsize'] = 11, 5
	readtime = False
	readitem = 1
	imagefolder = 'success_ratio'
	Ylabel = 'Success Ratio'

	Draw()
